# Release: https://github.com/scrtlabs/secretai-chat-docker/releases/tag/v1.1.2
# Workflow URL: https://github.com/scrtlabs/secretai-chat-docker/actions/runs/16880379277
# Commit: https://github.com/scrtlabs/secretai-chat-docker/commit/31ca82ad21f0af0db47bec72355cd1038b23cee0
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secretai-chat-docker@sha256:fe91d2c4ffbc544d8b7149b9c0cfded64b61eef4a76d6a30091a7a59aec000bd
    ports:
      - '8000:8000'
